# Generated by Django 4.1.7 on 2023-02-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loans",
            name="color",
        ),
        migrations.AddField(
            model_name="loans",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
